apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hopps
spec:
  chart:
    spec:
      chart: hopps
      sourceRef:
        kind: HelmRepository
        name: hopps
      version: 0.2.3
  interval: 1m0s
  values:
    # az-document-ai
    azDocumentAi:
      image:
        tag: "817"
      envFrom:
        - secretRef:
            name: az-document-ai
    # org
    org:
      image:
        tag: "817"
      envFrom:
        - secretRef:
            name: org
      envVars:
        # Database secrets
        - name: quarkus.datasource.jdbc.url
          value: jdbc:postgresql://postgres-cluster-rw:5432/org?loggerLevel=OFF&sslmode=require
        - name: quarkus.swagger-ui.path
          value: /q/swagger-ui
        - name: quarkus.smallrye-openapi.path
          value: /q/openapi
        - name: quarkus.datasource.username
          valueFrom:
            secretKeyRef:
              name: org-db-secret
              key: username
        - name: quarkus.datasource.password
          valueFrom:
            secretKeyRef:
              name: org-db-secret
              key: password
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://demo.${DOMAIN_2}"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
        ingressClassName: nginx
        hosts:
          - host: api.demo.${DOMAIN_2}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: api-tls
            hosts:
              - api.demo.${DOMAIN_2}
      managementIngress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/server-snippet: |
            location = /swagger {
              return 302 /q/swagger-ui;
            }
        hosts:
          - host: api.demo.${DOMAIN_2}
            paths:
              - path: /q/swagger-ui
                pathType: Prefix
              - path: /q/openapi
                pathType: Prefix
        tls:
          - secretName: api-tls
            hosts:
              - api.demo.${DOMAIN_2}
    # disable subchart for postgresql
    postgresql-org:
      enabled: false
    # frontend
    frontend:
      image:
        tag: "825"
      envFrom:
        - secretRef:
            name: frontend
      podSecurityContext:
        fsGroup: 1000
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        ingressClassName: nginx
        hosts:
          - host: demo.${DOMAIN_2}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: frontend-tls
            hosts:
              - demo.${DOMAIN_2}
    zugferd:
      image:
        tag: "817"
      envFrom:
        - secretRef:
            name: zugferd
    # use already available keycloak
    keycloak:
      enabled: false