apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hopps-liberlo
resources:
  - ../../base/hopps
  - namespace.yaml
  # create database
  - cnpg-cluster.yaml
  - database.yaml
# patch files matching the environment
patches:
  - path: helm-release.yaml
# create all needed secrets with fix name
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: fin
    envs:
      - secrets/fin-secret-encrypted.env
  - name: org
    envs:
      - secrets/org-secret-encrypted.env
  - name: az-document-ai
    envs:
      - secrets/az-document-ai-secret-encrypted.env
  - name: frontend
    envs:
      - secrets/frontend-secret-encrypted.env
  - name: openfga
    envs:
      - secrets/openfga-secret-encrypted.env
  - name: postgres-operator-secret
    envs:
      - secrets/postgres-cluster-secret-encrypted.env
  - name: openai-api-key
    envs:
      - secrets/openai-api-key-encrypted.env
  # basic auth for kafka-ui
  - name: kafka-ui-auth
    envs:
      - secrets/kafka-ui-secret-encrypted.env
  # database credentials
  - name: fin-db-secret
    envs:
      - secrets/db/fin-db-secret-encrypted.env
  - name: org-db-secret
    envs:
      - secrets/db/org-db-secret-encrypted.env
  - name: keycloak-db-secret
    envs:
      - secrets/db/keycloak-db-secret-encrypted.env
  - name: openfga-db-secret
    envs:
      - secrets/db/openfga-db-secret-encrypted.env
