apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hopps
spec:
  chart:
    spec:
      chart: hopps
      sourceRef:
        kind: HelmRepository
        name: hopps
      version: 0.1.4
  interval: 1m0s
  values:
    openfgaEnabled: true
    openfga:
      # only run one pod for now
      replicaCount: 1
      # use postgresql-database
      datastore:
        engine: postgres
        uriSecret: openfga
        # https://github.com/openfga/helm-charts/issues/100
        migrationType: "initContainer"
      postgresql:
        enabled: false
    keycloak:
      command:
        - "/opt/keycloak/bin/kc.sh"
        - "start"
        - "--http-port=8080"
        - "--hostname-strict=false"
      extraEnv: |
        - name: JAVA_OPTS_APPEND
          value: >-
            -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
      # configure proxy through env variables
      proxy:
        enabled: true
        mode: xforwarded
