apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hopps
spec:
  chart:
    spec:
      chart: hopps
      sourceRef:
        kind: HelmRepository
        name: hopps
      version: 0.2.7
  interval: 1m0s
