# keycloak
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgres-cluster
  encoding: UTF8
---
# org
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: org
spec:
  name: org
  owner: org
  cluster:
    name: postgres-cluster
  encoding: UTF8
