apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
spec:
  teamId: "hopps"
  postgresql:
    version: "17"
    parameters:
      # depending on application that can cause issues
      password_encryption: scram-sha-256
  numberOfInstances: 1
  volume:
    size: "50Gi"
    storageClass: "longhorn"
  allowedSourceRanges: # load balancers' source ranges for both master and replica services
    - 10.0.0.0/16
  #  requests:
  #    cpu: 100m
  #    memory: 100Mi
  #  limits:
  #    cpu: 500m
  #    memory: 500Mi
  # create users
  users:
    # namespace.name: roles
    hopps-dev.org: [ ]
    hopps-dev.fin: [ ]
    hopps-dev.openfga: [ ]
    hopps-dev.keycloak: [ ]
  databases:
    # name: owner (namespace.name)
    # namespace notation is part of user name
    org: hopps-dev.org
    fin: hopps-dev.fin
    openfga: hopps-dev.openfga
    keycloak: hopps-dev.keycloak
